### ISSUE TITLE
about episode and the step size of each episode defined、plot

### ISSUE THREAD

**Issue by xiaomaohouhou** [bilalkabas/DRL-Nav#2]
Hi,
I'd like to consult you two questions. Where are the number of episode and the step size of each episode defined? Can you share the plot file of the result(such as loss、mean reward、success rate )? 
Thank you very much, my friend

**Comment by bilalkabas** [comment]
Hi,

1.  The step size of an episode varies depending on the agent's actions, i.e. the episode is terminated when the drone collides with walls or it goes through a hole successfully. Therefore, there is no fixed step size for episodes. Training is performed over a specific number of steps not episodes. In below lines, the `total_timesteps` refer to the number of steps to be reached to finish training.

https://github.com/bilalkabas/DRL-Nav/blob/11089e02141c6373eb5fe6b70c107ce27090d5b0/train.py#L75-L79

2. For the mean reward per episode, see the below figure.

<img src="https://user-images.githubusercontent.com/53112883/178573291-66978bda-f6de-41d4-80e9-75417e2133e2.png" width="400">

The loss is not so descriptive for reinforcement learning and I cannot find it at the moment. For the success rate, I do not have a direct graph but it would look like the mean episode reward as the reward computation includes success and fail scenarios.
